# This file should be used (copy-pasted) in motion_analysis
STANDING_PERSON_HEIGHT: 120
OUTOFBED_LEFT: 480
OUTOFBED_RIGHT: 639
CUPX: 440
CUPY: 280
CUPR: 10
SENSITIVITY: 350
CUPTHRESHOLD: 800
CUPTHRSCOUNT: 375

